POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "sindhu",
  "password": "sindhu@11"
}
###

POST http://localhost:3000/
Content-Type: application/json


{
    "userId": 0,
    "id": 0,
    "title": "python",
    "body":"react,html,css"
  }


###

GET http://localhost:3000/posts/


###

GET http://localhost:3000/posts/1
###
DELETE http://localhost:3000/logout